name: Lint and build

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - name: Install dependencies and lint files
        run: |
          npm ci
          npm run lint
      - name: Build with Docker
        run: docker build .
